spring.application.name=vehicle-tracking-backend
server.port=8081

# Vehicle Tracking projesine ait Kafka broker adresi
spring.kafka.bootstrap-servers=localhost:29092

# PRODUCER AYARLARI
# Kafka mesajinin key kismi String olacak.
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Kafka mesajinin value kismi artik LocationEvent nesnesi olacak.
# JacksonJsonSerializer, Java nesnesini JSON byte[] verisine dönü?türür.
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# CONSUMER AYARLARI
# Kafka mesaj?n?n key k?sm?n? String'e dönü?türür.
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka'dan gelen JSON verisini tekrar Java nesnesine dönü?türür.
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# Consumer JSON'u hangi Java sinifina dönüstürecegini bilsin.
spring.kafka.consumer.properties[spring.json.value.default.type]=com.example.vehicletrackingbackend.event.LocationEvent

# Güvenlik nedeniyle JSON deserializer yaln?zca izin verilen package'lardaki s?n?flar? olu?turur.
# Biz kendi event package'?m?za izin veriyoruz.
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.example.vehicletrackingbackend.event

# Yeni bir consumer group olu?ursa geçmi? mesajlar yerine yeni gelen mesajlardan ba?las?n.
spring.kafka.consumer.auto-offset-reset=latest

# =========================
# POSTGRESQL AYARLARI
# =========================

# Vehicle Tracking projesinin PostgreSQL veritaban? adresi
spring.datasource.url=jdbc:postgresql://localhost:5433/vehicle_tracking

spring.datasource.username=vehicle_user

spring.datasource.password=vehicle_pass

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true