spring.application.name=vehicle-tracking-backend
server.port=8081

# Vehicle Tracking projesine ait Kafka broker adresi
spring.kafka.bootstrap-servers=localhost:29092

# PRODUCER AYARLARI
# Kafka mesajinin key kismi String olacak.
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Kafka mesajinin value kismi artik LocationEvent nesnesi olacak.
# JacksonJsonSerializer, Java nesnesini JSON byte[] verisine dönüştürür.
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# CONSUMER AYARLARI
# Kafka mesajının key kısmını String'e dönüştürür.
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka'dan gelen JSON verisini tekrar Java nesnesine dönüştürür.
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# Consumer JSON'u hangi Java sinifina dönüstürecegini bilsin.
spring.kafka.consumer.properties[spring.json.value.default.type]=com.example.vehicletrackingbackend.event.LocationEvent

# Güvenlik nedeniyle JSON deserializer yalnızca izin verilen package'lardaki sınıfları olusturur.
# Biz kendi event package'ımıza izin veriyoruz.
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.example.vehicletrackingbackend.event

# Yeni bir consumer group oluşursa geçmiş mesajlar yerine yeni gelen mesajlardan baslasın.
spring.kafka.consumer.auto-offset-reset=latest

# =========================
# POSTGRESQL AYARLARI

# Vehicle Tracking projesinin PostgreSQL veritabanı adresi
spring.datasource.url=jdbc:postgresql://localhost:5433/vehicle_tracking

spring.datasource.username=vehicle_user

spring.datasource.password=vehicle_pass

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true